# Generated by Django 4.1.2 on 2024-10-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTecnologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('energia_utilizada', models.CharField(max_length=100)),
                ('obsolescencia', models.IntegerField()),
                ('pais_productor', models.CharField(max_length=100)),
                ('huella_carbono', models.FloatField()),
            ],
        ),
    ]
